version: '3.9'
services:
    dbt-docker:
        image: dannylee1020/baseball_dbt:latest
        volumes:
            - ${HOME}/.config/gcloud:/root/.config/gcloud
        build: .
        restart: always
